### ISSUE TITLE
Question: should calling reveal but public or onlyOwner?

### ISSUE THREAD

**Issue by santekotturi** [tubby-cats/batch-nft-reveal#3]
I'm using v2 of the chainlink VRF and planning on funding the subscription manager with enough link to reveal the entire collection (a 10k collection being revealed in batches of 200). I'm curious if revealNextBatch should be `public` or `public onlyOwner`. My concern is that if the sub manager has enough link, then someone could just reveal the entire collection. Is it considered bad form to prevent anyone from calling reveal?

```
    function revealNextBatch() public {
        require(
            maxKiftables >= (lastTokenRevealed + REVEAL_BATCH_SIZE),
            "maxKiftables too low"
        );

        // requesting randomness
        COORDINATOR.requestRandomWords(
            s_keyHash,
            s_subscriptionId,
            3, // requestConfirmations
            100000, // callbackGasLimit         
            1 // numWords
        );
    }
    ```

**Comment by 0xngmi** [comment]
Allowing anyone to reveal is not an issue, only possible problem is that someone could use it to snipe unrevealed rares and gain a smol edge this way
